### ISSUE TITLE
test fails

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-novactf#29]
both imod and novactf plugins are from devel branch

```
** Running command: 'python3 /lmb/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/apps/pw_protocol_run.py "/lmb/home/gsharov/cephfs/ScipionUserData/projects/TestNovaCtfReconstructionWorkflow" "Runs/000002_ProtImportTs/logs/run.db" 2'
[   FAILED ] TestNovaCtfReconstructionWorkflow.setUpClass

Traceback (most recent call last):
File "/public/EM/Scipion/miniconda3/envs/.scipion3env/lib/python3.8/unittest/suite.py", line 163, in _handleClassSetUp
setUpClass()
File "/lmb/home/gsharov/soft/scipion-em-plugins/scipion-em-novactf/novactf/tests/test_protocols_novactf.py", line 145, in setUpClass
cls.protCTFEstimation = cls._runCTFEstimation(
File "/lmb/home/gsharov/soft/scipion-em-plugins/scipion-em-novactf/novactf/tests/test_protocols_novactf.py", line 70, in _runCTFEstimation
cls.protCTFEstimation = cls.newProtocol(imod.protocols.ProtImodCtfEstimation,
AttributeError: module 'imod.protocols' has no attribute 'ProtImodCtfEstimation'
```

**Comment by fede-pe** [comment]
Should be fixed now in devel branch. Thanks for reporting.
